// <auto-generated />
using GraphQL_HotChocolate_ASP.NET_CORE_.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLHotChocolateASP.NETCORE.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230118171312_InitiatMigration")]
    partial class InitiatMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQL_HotChocolate_ASP.NET_CORE_.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "Center Forward",
                            Name = "Samantha El-Shawray"
                        },
                        new
                        {
                            Id = 2,
                            Designation = "Central Devensive Midfield",
                            Name = "Unai Simpsom"
                        },
                        new
                        {
                            Id = 3,
                            Designation = "Holding Midfield",
                            Name = "Given Mkron"
                        },
                        new
                        {
                            Id = 4,
                            Designation = "Weeket Keeper",
                            Name = "Ashwin Randa"
                        },
                        new
                        {
                            Id = 5,
                            Designation = "First Order batsman",
                            Name = "Rahul Dev"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
